version: '3.8'

services:
  chatapp:
    build: .
    ports:
      - "5002:5002"
    networks:
      - labnet
    restart: unless-stopped

  ssh:
    image: linuxserver/openssh-server
    container_name: ssh-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Guayaquil
      - PASSWORD_ACCESS=true
      - USER_NAME=bcmalla
      - USER_PASSWORD=admin123
    ports:
      - "2222:2222"
    networks:
      - labnet
    restart: unless-stopped

  ftp:
    image: fauria/vsftpd
    container_name: ftp-server
    environment:
      - FTP_USER=bcmalla
      - FTP_PASS=admin123
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - ./ftpdata:/home/vsftpd
    networks:
      - labnet
    restart: unless-stopped

networks:
  labnet:
    driver: bridge
